vshymanskyy/TinyGSM

TinyGsmClientSIM800.h
possible usage: 
``` c
float vBatt = modem.getBattVoltage() / 1000.0;
```
=> Add getBattVoltage for SIM800

src/TinyGsmClientA6.h, src/TinyGsmClientESP8266.h, src/TinyGsmClientM590.h, src/TinyGsmClientSIM800.h, src/TinyGsmClientU201.h
Added timeout in streamSkipUntil. I use SoftwareSerial and sometime get device to hang because of doing TINY_GSM_YIELD infinitely.
=> add timeout to streamSkipUntil

examples/AllFunctions/AllFunctions.ino, examples/SIM7000-ESP32/AllFunctions/AllFunctions.ino, examples/SIM7000-ESP32/Diagnostics/Diagnostics.ino, src/TinyGsmClient.h, src/TinyGsmClientSIM7000.h
Hello Volodymyr,
I just did a quick duplication of the SIM800 client library and rewrote some pieces for SIM7000.
Could not test this with a working nb-iot network yet but gsm works.
I will for sure go on with my work because i need it for my work.
Cheers
Chris
=> Adding sim7000 e

src/TinyGsmClientUBLOX.h
SARA-R4 / SARA-N4 => +CFUN=16, 19 and 127 are not supported.
Added +URAT possibility to choose the Radio rechnology.
=> fix CFUN restart on R4xxx and add +URAT options

examples/FileDownload/FileDownload.ino
The FileDownload example can have a case when it will fail during the parsing of the response headers.
The main problem is that the `while (client.available())` loop for the response header can exit prematurely if the client can't keep up with the loop.
I made the response header loop use a rolling buffer to look at the header lines, and includes a configurable client response timeout.
=> Fixed data acquisition race condition in FileDownload example -- Fixes #301

src/TinyGsmClientSIM800.h
Add NTPServerSync() function to sync datetime with NTP server.
=> Add NTP server date time sync function

src/TinyGsmClientSIM800.h, src/TinyGsmCommon.h
Added support to get IMSI information on SIM800 and SIM808 modules.
=> Added support for IMSI information on SIM800 and SIM808 modules

examples/AllFunctions/AllFunctions.ino, src/TinyGsmClientA6.h, src/TinyGsmClientBG96.h, src/TinyGsmClientESP8266.h, src/TinyGsmClientM590.h, src/TinyGsmClientM95.h, src/TinyGsmClientMC60.h, src/TinyGsmClientSIM5360.h, src/TinyGsmClientSIM7000.h, src/TinyGsmClientSIM7600.h, src/TinyGsmClientSIM800.h, src/TinyGsmClientSIM808.h, src/TinyGsmClientSaraR4.h, src/TinyGsmClientSequansMonarch.h, src/TinyGsmClientUBLOX.h, src/TinyGsmClientXBee.h, src/TinyGsmCommon.h
Hi! As we discussed in #346 I added new functionality with CRTP. Also, virtual destructors had to go. They do more harm than good in embedded environment, besides all `TinyGsm` classes are trivially destructible anyway.
=> UTF-8 SMS suport for SIMxxx modules

src/TinyGsmClientSIM800.h
the BTS location might help a little if getting errors via device reading
=> in case of erroneous return of device location

src/TinyGsmModem.tpp
After did some test with a SIM808 GPS functions, I noticed that there was a problem with streamGetFloatLength and streamGetIntLength methods when trying to parse GPS data.
If the stream is not available, read functions were not working properly. 
Now, a timeout is used to wait for stream availability.  Also the common code has been refactored in a new function. 
Finally, dynamic buffer size and some checks have been added to avoid memory corruption.
=> Fixed problem with streamGetFloatLength and streamGetIntLength functions

src/TinyGsmClientA6.h, src/TinyGsmClientBG96.h, src/TinyGsmClientESP8266.h, src/TinyGsmClientM590.h, src/TinyGsmClientM95.h, src/TinyGsmClientMC60.h, src/TinyGsmClientSIM5360.h, src/TinyGsmClientSIM7000.h, src/TinyGsmClientSIM7600.h, src/TinyGsmClientSIM800.h, src/TinyGsmClientSaraR4.h, src/TinyGsmClientSequansMonarch.h, src/TinyGsmClientUBLOX.h, src/TinyGsmClientXBee.h, src/TinyGsmModem.tpp
Added method to set the phone functionality (specially important when trying to put some modules into sleep mode) 
Tested on SIM808.
=> Added setPhoneFunctionality method

src/TinyGsmGPS.tpp
=> passage variables by reference

src/TinyGsmClientA6.h, src/TinyGsmClientBG96.h, src/TinyGsmClientESP8266.h, src/TinyGsmClientM590.h, src/TinyGsmClientM95.h, src/TinyGsmClientMC60.h, src/TinyGsmClientSIM5360.h, src/TinyGsmClientSIM7000.h, src/TinyGsmClientSIM7600.h, src/TinyGsmClientSIM800.h, src/TinyGsmClientSaraR4.h, src/TinyGsmClientSequansMonarch.h, src/TinyGsmClientUBLOX.h, src/TinyGsmClientXBee.h, src/TinyGsmModem.tpp
When using pin it's necessary to pass it on restart function. Otherwise, it will always fail.
=> Added pin parameter on restart() (necessary for init() with pin)

src/TinyGsmBluetooth.tpp, src/TinyGsmClientSIM808.h
I have added some basic functionality on SIM808 bluetooth. I have also code for scanning bluetooth devices, pairing and connect (but I need to refactor it before open a new merge request). 
It is important to disable bluetooth if you don't need it because it is enabled by default (and consuming power) 
Please, do not hesitate giving me some corrections or recommendations if it's necessary.
=> First SIM808 bluetooth support commit. Template class and basic functionality

src/TinyGsmClientSIM7000.h
SIM7000: added methods to get some connection preferences, plus the current connection technology.
Fixes #504
=> SIM7000: added methods to get some connection preferences

src/TinyGsmClient.h, src/TinyGsmClientSIM7000.h
Hi,
I have based this pr on the great code by @marmotton and @javipelopi.
I have just:
* Packaged their code, aligning it also to the newer master version
* Performed some minor cleanup
* Performed a good debug
* Supported factory reset of the modem
Now it works perfectly with MQTT both with and without TLS.
Fixes #437
Fixes #474 
Fixes #495
Regards
=> SIM7000: TLS support plus other minor improvements

src/TinyGsmClientSIM7000.h
Copied from TinyGsmClientSIM800.h
=> Added NTPServerSync() and related methods to Sim7000 implementation 

src/TinyGsmClientSequansMonarch.h
Use data mode instead of text mode to be able to send any content such
as raw binary. This will allow us to use TinyGSM with ArduinoBearSSL and
ArduinoMqtt.
It should be noted that for an unclear reason GSM_NL must be set to '\n'
instead of '\r\n' to avoid "CME ERROR: operation not supported" in this
mode with the Monarch GMS01Q.
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
=> TinyGsmClientSequansMonarch.h: use data mode

src/TinyGsmFifo.h, src/TinyGsmTCP.tpp
To implement peek() as in https://github.com/vshymanskyy/TinyGSM/issues/396
=> To implement peek()

library.json, src/TinyGsmClientSIM5360.h
I have added the code for GPS location for SIM 5320. I have tested and it works
=> Sim5320 GPS Location Update

src/TinyGsmClient.h, src/TinyGsmClientA7672x.h, src/TinyGsmGPRS.tpp
- SSL Compatible
Limitations:
- GNSS functions not implemented
- Battery functions not implemented
=> Support for SIMCom A7672SA
