vshymanskyy/TinyGSM

- src/TinyGsmClientSIM800.h
Set default alphabet to `GSM` for send SMS function as per AT command manual. 
Even now AllFunctions.ino won't work as the default alphabet was set to `HEX` in sendUSSD function and never changed again.
> Set an alphabet for SMS sending to "GSM" for SIM800/808 

- examples/AllFunctions/AllFunctions.ino
- keywords.txt
- src/TinyGsmClientSIM800.h
Adds functionality to fetch the Date & Time from Network (you can also get this from the GPS Location, but this requires connection to APN)
The function is called _getGSMDateTime_ and it accepts a single parameter which is an enumeration to specify the format:
- DATE_FULL **Returns the full Date & Time** 
- DATE_TIME **Returns the Time only** 
- DATE_DATE **Returns the Date only**
> Added Network Time Fetching for SimXXX

- src/TinyGsmClientBG96.h
- bool isGprsConnected() is now returning correct status     
- bool modemGetConnected() is now working as expected
See #343
> Fix BG96 bugs

- src/TinyGsmClientMC60.h
A batch of fixes for MC60, made according to documentation.
1) It is needed to specify for the modem that it should work as 'client' in gprsConnectImpl:
```
// Modem is used as a client
sendAT(GF("+QISRVC=1"));
if (waitResponse() != 1) { return false; }
```
2) In modemConnect, before opening the connection, it is required to specify how 'host' parameter should be treated: as a host or as an IP ddress:
```
// By default, MC60 expects IP address as 'host' parameter. 
// If it is a domain name, "AT+QIDNSIP=1" should be executed.
// "AT+QIDNSIP=0" is for dotted decimal IP address.
IPAddress addr;
sendAT(GF("+QIDNSIP="), (addr.fromString(host)?0:1));
if (waitResponse() != 1) { return false; }
```
3) During sending process 'mux' should be passed to +QISACK if multiply connections used:
` …
> FIX for issue #371: MC60 is not working with this library

- src/TinyGsmCommon.h
This pull request disable the memory optimization defines for ATmega4809 (eg Arduino Nano Every)
> disable memory optimizations on ATmega4809

- src/TinyGsmClientBG96.h
We have some issue with BG96 used in Japan.
We do not have 2G here and some operator provides SIM without SMS, another operator does not provide 3G, which causes `CREG` returns 0,2 (searching) or 0,3 (denied) even though PS attach succeeded.
To check registration status in such situation, we could use `CEREG` like it is done for "u-blox SARA-R4" module.
I referred `TinyGsmClientSaraR4.h` for this patch.
Could you consider to merge this, please?
Many thanks to @SRGDamia1 !
> use CEREG first to check registration status for BG96

- src/TinyGsmClientSequansMonarch.h
There is an issue in the handling of `+SQNSS` answer: the `sock->sock_connected` state will always be set to the state of the last
socket. This will prevent any communication.
Fix this issue by checking that muxNo is equal to mux before updating.
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
> src/TinyGsmClientSequansMonarch.h: fix connection handling

- src/TinyGsmModem.tpp
As specified in the ETSI standards (e.g. ETSI TS 127 001), `CREG` and `CEREG` responses can contain optional parameters:
`+CEREG:         <n>,<stat>[,<tac>,<ci>[,<AcT>]]`
For example, the Monarch GMS01Q returns the following response:
`+CEREG: 2,1,"3982","00DF3B03",7`
This results in TinyGSM setting state as '7' instead of 1 preventing any connection.
Fix this by picking the next integer after the first ',' which will always works (with or without optional parameters)
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
> src/TinyGsmModem.tpp: fix registration state

- src/TinyGsmSMS.tpp
Some telecom operators respond to a ussd request longer than 128 characters. In this case, we will not be able to exit the TinyGsmDecodeHex8bit function. It is necessary to change the declaration of the increment: "uint8_t i" -> "uint16_t i"
With function TinyGsmDecodeHex16bit i don't work, but for 16 bit messages we have only 64 char, if over, we never exit from this functions :)
> fix bug for ussd answers over 127 chars

- src/TinyGSM.h
- src/TinyGsmClientUBLOX.h
Hi,
this is a minor pr, with these features:
* Added method to UBLOX set the radio access technology
* Added missing `TinyGSM.h`: it is required for installation with tools like `arduino-cli` (which I actually use :-) )
* Removed a print (used to notify URC) which (IMHO) seems to print "too noise" on the debug serial (at least with `SARA U201`).
* Removed a duplicated print (modem model name: already printed in `initImpl()`, where this print actually makes sense, IMHO).
What's missing:
* A "twin method" to get the current radio access technology. I have done some tests, but unfortunately I was not able to get this info... so for the moment the method is left as a "TODO"
> Added ublox method to set technology + other minor improvements

- src/TinyGsmClientSequansMonarch.h
The mux value is corrected if it is out of the supported range, but the uncorrected value was used to store the connection object. This caused subsequent dereferences of the corrected mux index to access incorrect data or dereference a null pointer.
> Fix incorrect memory access in Sequans Monarch code

- README.md
- src/TinyGsmClientSIM7600.h
Add support for voice calls for SIM7600. This implements
* Answering calls
* Initiating calls
* Hanging up
* Sending DTMF tones
> Add phone call implementation for SIM7600

- src/TinyGsmClientBG96.h
> Fix parsing AT-command for getting GPS time in BG96

- src/TinyGsmClient.h
- src/TinyGsmClientBG96.h
I noticed no-one seems to have has solved this problem yet. The challenge seems to come from how BG96 sets up SSL connection compared to other modems. Instead of using some AT command to configure SSL and then doing the rest with the TCP at commands, it has a whole set of different commands for SSL. This is tricky to integrate with how TinyGsm is currently structured.
I have redefined modemSend, modemRead, modemGetConnected and modemGetAvailable and felt like I almost got everything connected until I noticed that it is very difficult to make the TinyGsmTCP write and read functions call these functions of we are using GsmClientSecureBG96 instead of GsmClientBG96 without breaking core functionality for everything else.
I have also edited modemConnect and gprsConnectImpl but they seem to …
> BG96 SSL secure socket connection for AWS connection with certificates (in progress)

- src/TinyGsmClientSIM7000.h
- src/TinyGsmClientSIM7000SSL.h
- src/TinyGsmClientSIM7080.h
- src/TinyGsmClientSIM70xx.h
- src/TinyGsmNTP.tpp
Hello @SRGDamia1 @vshymanskyy thank you for your great work.
This PR fixes two issues with the NTPServerSync function.
1) Prior to this PR, you could not set negative timezones because the passed value was byte (which translates to uin8_t). Now the value passed it's an Int so you can set any timezone (from -47 to +48).
2) On old SIM800 the return code of +CNTP was always: `+CNTP: <code>` but now with newer modules you could also get the network time attached to the response like this: `+CNTP: <code>[,<time>]` . What I did to keep backward compatibility is to look for the ',' and remove all the leading characters if found. If not, assume the reply was just the `<code>`.
It is working perfectly on my SIM7000. 
Thanks
Gonzalo
> Fix NTPServerSync

- src/TinyGsmClientSIM7600.h
https://www.simcom.com/product/SIM7600X-PCIE.html
SIM7500_SIM7600 Series_AT Command Manual_V3.00
- `AT+CGAUTH=<cid>[,<auth_type>[,<passwd>[,<user>]]]`
- `AT+CGAUTH=,,<user>,<passwd> (for CDMA1x-EvDo)`
If not CDMA1, password should come first.
> password then user when cid is set

- src/TinyGsmClientSIM7600.h
1. SIM7600 delay in `restartImpl()` is not enough, a real module takes at least 23 seconds to reboot before it starts to respond to any AT commands.
2. (Fixes #624) The `getGPSImpl(...)` method expects two extra `","` in the response that breaks the `iaccuracy` variable and also causes it to skip the `OK` part in the end of the response that leads to the 3-seconds waiting until the timeout occurs. After that the `waitResponse()` in the last line of that method also does not receive the proper `OK` and also waits 1 extra second until the timeout.
> SIM7600 Protocol enhancements (Fixes #624)

- src/TinyGsmClientSIM7600.h
In the sim7600 modem, when the location is being obtained recurrently from the second iteration, it does not process the cardinal points correctly.
https://github.com/vshymanskyy/TinyGSM/issues/566
https://github.com/vshymanskyy/TinyGSM/issues/641
> Fix cardinal points in location by gps for sim7600

- examples/AllFunctions/AllFunctions.ino
- examples/BlynkClient/BlynkClient.ino
- examples/FileDownload/FileDownload.ino
- examples/HttpClient/HttpClient.ino
- examples/MqttClient/MqttClient.ino
- examples/WebClient/WebClient.ino
- src/TinyGsmBluetooth.tpp
- src/TinyGsmClient.h
- src/TinyGsmClientSIM808.h
- src/TinyGsmClientSaraR5.h
- src/TinyGsmClientSequansMonarch.h
- src/TinyGsmClientUBLOX.h
- src/TinyGsmFifo.h
- src/TinyGsmSMS.tpp
- src/TinyGsmTCP.tpp
This implementation is very similar to the SARA R4 module and the generic ublox implementation.
Test setup: a custom ESP32 module and a MIKROE LTE IOT 5 CLICK module which has a ublox SARA-R510M8S (incl. GNSS) on-board
I was able to test the SMS/TCP(&MQTT)/GNSS&GPS functionalities using the AllFunctions examples code.
The other example code files (where the SARA R5 can be used) have been updated but not tested!
Also there are some changes to other files which do not concern the functionality of the SARA R5, but were made because I've formatted all files using `clang-format`.
If there are any questions, I will gladly try to answer them.
> Added support for u blox SARA R5 modules

- src/TinyGsmClientSIM7000.h
- src/TinyGsmClientSIM7600.h
- src/TinyGsmModem.tpp
Add support for "SEND FAIL" response from SIM7000 modem
Without this change the transmission pauses for 1 second when "SEND FAIL" is received from the modem as the code ends up in the unhandled case in waitResponse() after the default 1 second timeout. This significantly reduces the possible throughput.
> Avoid unnecessary timeout when receiving "SEND FAIL" response from SIM7000 modem
